# Generated by Django 3.1.5 on 2021-03-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='creater_on',
            new_name='created_on',
        ),
    ]
